[package]
name = "filecrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
dryoc = "0.7.2"
aes-gcm-siv = "0.11.1"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
libc = "0.2"
zeroize = { version = "1.8", features = ["zeroize_derive"] }
rpassword = "7.3"