
[package]
name = "ai"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm-siv = "0.11.1"
anyhow = "1.0"
argon2 = "0.5"
clap = { version = "4.5", features = ["derive"] }
dryoc = "0.7"
libc = "0.2"
rpassword = "7.4"
zeroize = { version = "1.8", features = ["zeroize_derive"] }






